Update Build_ax6000_immortalwrt.yml

diff --git a/.github/workflows/Build_ax6000_immortalwrt.yml b/.github/workflows/Build_ax6000_immortalwrt.yml
--- a/.github/workflows/Build_ax6000_immortalwrt.yml
+++ b/.github/workflows/Build_ax6000_immortalwrt.yml
@@ -93,7 +93,7 @@ jobs:
       env: 
         REPO_URL: https://github.com/immortalwrt/immortalwrt
       run: |
-        git clone --depth 1 -b v24.10.2 --single-branch --filter=blob:none $REPO_URL immortalwrt || { echo 'Git clone failed!'; exit 1; }
+        git clone --depth 1 -b v24.10.3 --single-branch --filter=blob:none $REPO_URL immortalwrt || { echo 'Git clone failed!'; exit 1; }
         cd immortalwrt
       #echo "src-git helloworld https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
       #echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> ./feeds.conf.default
@@ -116,12 +116,12 @@ jobs:
       run: |
         ./scripts/feeds install -a
 
-    - name: Import external feeds - OpenClash
-      working-directory: ./immortalwrt
-      run: |
-        git clone --depth=1 https://github.com/vernesong/OpenClash.git package/OpenClash
-        mv package/OpenClash/luci-app-openclash package
-        rm -rf package/OpenClash  
+    #- name: Import external feeds - OpenClash
+    #  working-directory: ./immortalwrt
+    #  run: |
+    #    git clone --depth=1 https://github.com/vernesong/OpenClash.git package/OpenClash
+    #    mv package/OpenClash/luci-app-openclash package
+    #    rm -rf package/OpenClash  
 
     # msd_lite 必须放在feeds命令后，immoralwrt 默认添加了 msd_lite，使用 msd_lite 收看 IPTV
     #- name: Import external feeds - msd_lite
